version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-browsers
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - run:
          name: install imagemagick
          command: sudo apt-get install imagemagick ghostscript
      - run:
          name: tests
          command: bundle exec rake
      - run:
          name: audit
          command: bundle exec bundle-audit update && bundle exec bundle-audit check
      - ruby/rubocop-check
